<?php

class aprsSymbol {

  function __construct() {

    // Define Constants
    $aprsSymbolTable = array(
      '/' => array(
        '!' => "POLICE",
        '"' => "RESERVED",
        '#' => "DIGI",
        '$' => "PHONE",
        '%' => "DX_CLUSTER",
        '&' => "HF_GATEWAY",
        '\'' => "SMALL_AIRCRAFT",
        '(' => "MOBILE_SATELLITE_STATION",
        ')' => "WHEELCHAIR",
        '*' => "SNOWMOBILE",
        '+' => "RED_CROSS",
        ',' => "BOY_SCOUTS",
        '-' => "HOUSE_QTH",
        '.' => "X",
        '/' => "RED_DOT",
        '0' => "CIRCLE_0",
        '1' => "CIRCLE_1",
        '2' => "CIRCLE_2",
        '3' => "CIRCLE_3",
        '4' => "CIRCLE_4",
        '5' => "CIRCLE_5",
        '6' => "CIRCLE_6",
        '7' => "CIRCLE_7",
        '8' => "CIRCLE_8",
        '9' => "CIRCLE_9",
        ':' => "FIRE",
        ';' => "CAMPGROUND",
        '<' => "MOTORCYCLE",
        '=' => "RAILROAD_ENGINE",
        '>' => "CAR",
        '?' => "FILESERVER",
        '@' => "HC_FUTURE_PREDICT",
        'A' => "AID_STATION",
        'B' => "BBS_PBBS",
        'C' => "CANOE",
        'D' => "",
        'E' => "EYEBALL",
        'F' => "FARM_VEHICLE",
        'G' => "GRID_SQUARE",
        'H' => "HOTEL",
        'I' => "TCPIP",
        'J' => "",
        'K' => "SCHOOL",
        'L' => "PC_USER",
        'M' => "MACAPRS",
        'N' => "NTS_STATION",
        'O' => "BALLOON",
        'P' => "ALT_POLICE",
        'Q' => "TBD",
        'R' => "RECREATIONAL_VEHICLE",
        'S' => "SHUTTLE",
        'T' => "SSTV",
        'U' => "BUS",
        'V' => "ATV",
        'W' => "NATIONAL_WX_SERVICE_SITE",
        'X' => "HELO",
        'Y' => "YACHT",
        'Z' => "WINAPRS",
        '[' => "PERSON",
        '\\' => "TRIANGLE",
        ']' => "MAIL",
        '^' => "LARGE_AIRCRAFT",
        '_' => "WEATHER_STATION",
        '`' => "DISH_ANTENNA",
        'a' => "AMBULANCE",
        'b' => "BIKE",
        'c' => "INCIDENT_COMMAND_POST",
        'd' => "FIRE_DEPARTMENT",
        'e' => "HORSE",
        'f' => "FIRE_TRUCK",
        'g' => "GLIDER",
        'h' => "HOSPITAL",
        'i' => "IOTA",
        'j' => "JEEP",
        'k' => "TRUCK",
        'l' => "LAPTOP",
        'm' => "MIC-E_REPEATER",
        'n' => "NODE",
        'o' => "EOC",
        'p' => "ROVER",
        'q' => "GRID_SQ",
        'r' => "REPEATER",
        's' => "SHIP",
        't' => "TRUCK_STOP",
        'u' => "18_WHEELER",
        'v' => "VAN",
        'w' => "WATER_STATION",
        'x' => "XAPRS",
        'y' => "YAGI@QTH",
        'z' => "ALT_TBD",
        '{' => "",
        '|' => "TNC_STREAM_SWITCH_1",
        '}' => "",
        '~' => "TNC_STREAM_SWITCH_2"
			),
      '\\' => array(
        '!' => "EMERGENCY",
        '"' => "ALT_RESERVED",
        '#' => "ALT_DIGI",
        '$' => "BANK",
        '%' => "POWERPLANT",
        '&' => "IGATE",
        '\'' => "CRASH",
        '(' => "CLOUDY",
        ')' => "FIRENET",
        '*' => "SNOW",
        '+' => "CHURCH",
        ',' => "GIRL_SCOUTS",
        '-' => "HOUSE",
        '.' => "AMBIGUOUS",
        '/' => "WAYPOINT_DESTINATION",
        '0' => "CIRCLE",
        '1' => "",
        '2' => "",
        '3' => "",
        '4' => "",
        '5' => "",
        '6' => "",
        '7' => "",
        '8' => "NETWORK_NODE",
        '9' => "GAS_STATION",
        ':' => "HAIL",
        ';' => "PARK",
        '<' => "ADVISORY",
        '=' => "APRSTT_TOUCHTONE",
        '>' => "ALT_CAR",
        '?' => "INFO_KIOSK",
        '@' => "HURICANE",
        'A' => "OVERLAYBOX",
        'B' => "BLWNG SNOW",
        'C' => "COAST_GUARD",
        'D' => "DRIZZLE",
        'E' => "SMOKE",
        'F' => "FREEZING_RAIN",
        'G' => "SNOW_SHOWER",
        'H' => "HAZE",
        'I' => "RAIN_SHOWER",
        'J' => "LIGHTENING",
        'K' => "KENWOOD",
        'L' => "LIGHTHOUSE",
        'M' => "MARS",
        'N' => "NAVIGATION_BUOY",
        'O' => "ROCKET",
        'P' => "PARKING",
        'Q' => "QUAKE",
        'R' => "RESTAURANT",
        'S' => "SATELLITTE",
        'T' => "THUNDERSTORM",
        'U' => "SUNNY",
        'V' => "VORTAC",
        'W' => "NWS_SITE",
        'X' => "PHARMACY",
        'Y' => "RADIOS",
        'Z' => "",
        '[' => "W_CLOUD",
        '\\' => "GPS",
        ']' => "",
        '^' => "AIRCRAFT",
        '_' => "WX_SITE",
        '`' => "RAIN",
        'a' => "ARRL_ARES_WINLINK",
        'b' => "BLOWING",
        'c' => "CD_TRIANGLE",
        'd' => "DX_SPOT",
        'e' => "SLEET",
        'f' => "FUNNEL_CLOUD",
        'g' => "GALE_FLAGS",
        'h' => "HAMSTORE",
        'i' => "BOX",
        'j' => "WORKZONE",
        'k' => "SPECIAL_VEHICLE",
        'l' => "AREAS",
        'm' => "VALUE_SIGN",
        'n' => "OVERLAY_TRIANGLE",
        'o' => "SMALL_CIRCLE",
        'p' => "PARTIALY CLOUDED",
        'q' => "",
        'r' => "RESTROOMS",
        's' => "ALT_SHIP",
        't' => "TORNADO",
        'u' => "ALT_TRUCK",
        'v' => "ALT_VAN",
        'w' => "FLOODING",
        'x' => "WRECK",
        'y' => "SKYWARN",
        'z' => "ALT_SHELTER",
        '{' => "FOG",
        '|' => "ALT_TNC_STREAM_SWITCH_1",
        '}' => "",
        '~' => "ALT_TNC_STREAM_SWITCH_2"
			)
    );

    foreach( $aprsSymbolTable as $tableByte => $tableData) {
      foreach($tableData  as $iconByte => $iconText) {
        if(!empty($aprsSymbolTable[$tableByte][$iconByte])) {
          define($aprsSymbolTable[$tableByte][$iconByte], $tableByte.$iconByte);
        }
      }
    }
  }


	static function overlay($symbol, $overlay) {
		
	}

}